name: production
on:
  push:
    branches:
      - main

protection_rules:
  - type: required_reviewers
    reviewers:
      - dvorobiev

environment_variables:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  CAMERA_URL: ${{ secrets.CAMERA_URL }}
  CONFIDENCE_THRESHOLD: "0.5"
  IOU_THRESHOLD: "0.45" 