name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Записываем приватный ключ в файл и выставляем права доступа
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Добавляем сервер в known_hosts. Если ssh-keyscan завершится ошибкой, выводим предупреждение и продолжаем
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || echo "Warning: ssh-keyscan failed, continuing..."

      - name: Network Check
        run: |
          echo "Testing SSH port connectivity on ${{ secrets.SERVER_HOST }}..."
          nc -zv ${{ secrets.SERVER_HOST }} 22 || echo "Port 22 unreachable"

      - name: Deploy to server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            echo "Current directory: $PWD"
            cd /opt/bridge-status-bot || exit 1
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart bridge_bot
          EOF
