name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH directory
        run: |
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/.ssh
          chmod 600 /home/runner/.ssh/known_hosts
          ls -la /home/runner/.ssh
      
      - name: Debug SSH connection
        run: |
          echo "Testing SSH connection..."
          echo "Using host: ${{ secrets.SERVER_HOST }}"
          echo "Using username: ${{ secrets.SERVER_USER }}"
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} -p 22 -T 60 >> /home/runner/.ssh/known_hosts || echo "Error code: $?"
          cat /home/runner/.ssh/known_hosts
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          debug: true
          script: |
            echo "Current directory: $PWD"
            cd /opt/bridge-status-bot
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart bridge_bot 